WatchStore/Controllers/FeedBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchStore.Models;

namespace WatchStore.Controllers
{
    public class FeedBackController : Controller
    {
        dbQLBandhDataContext data = new dbQLBandhDataContext();
        // GET: FeedBack

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public ActionResult Lienhe()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Lienhe(FormCollection collection, LIENHE lh)
        {
            var hoten = collection["HoTen"];
            var email = collection["Email"];
            var dienthoai = collection["DienthoaiKH"];
            var phanhoi = collection["Mess"];
            
                lh.HoTen = hoten;            
                lh.Email = email;           
                lh.DienthoaiKH = dienthoai;
                lh.Mess = phanhoi;
                data.LIENHEs.InsertOnSubmit(lh);
                data.SubmitChanges();
               
        

            return this.Lienhe();
        }
    }
    
}

WatchStore/Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchStore.Models;


namespace WatchStore.Controllers
{
    public class NguoidungController : Controller
    {
        dbQLBandhDataContext data = new dbQLBandhDataContext();
        // GET: Nguoidung

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:yyyy/MM/dd}", collection["Ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên không được để trống!";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Tên đăng nhập không được để trống !";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Mật khẩu không được để trống !";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu!";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được để trống !";
            }
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Phải nhập số điện thoại !";
            }
            else
            {
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);
                data.KHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();

                return RedirectToAction("Dangnhap");
            }

            return this.Dangky();

        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập!";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Đăng nhập thành công";
                    Session["Taikhoan"] = kh;
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

WatchStore/Controllers/WatchStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchStore.Models;
namespace WatchStore.Controllers
{
    public class WatchStoreController : Controller
    {
        dbQLBandhDataContext data = new dbQLBandhDataContext();
        private List<DONGHO> Laydonghomoi(int count) => data.DONGHOs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        // GET: WatchStore
        public ActionResult Index()
        {
            var donghomoi = Laydonghomoi(8);
            return View(donghomoi);
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult SPtheochude(int id)
        {
            var dongho = from dh in data.DONGHOs where dh.MaCD == id select dh;
            return View(dongho);
        }
        public ActionResult Details(int id)
        {
            var dongho = from dh in data.DONGHOs where dh.MaDH == id select dh;
            return View(dongho.Single());
        }
        public ActionResult AboutUS()
        {
            return View();
        }
        public ActionResult Shop()
        {
            var donghomoi = Laydonghomoi(16);
            return View(donghomoi);
        }

    }
}

WatchStore/Views/WatchStore/AboutUS.cshtml
@{
    ViewBag.Title = "Về chúng tôi";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<!-- banner -->
<style>
    li {
        color: #9b59b6;
    }
</style>
<div class="banner_inner">
    <div class="services-breadcrumb">
        <div class="inner_breadcrumb">

            <ul class="short">
                <li>
                    @Html.ActionLink("Trang Chủ", "Index", "WatchStore")
                    <i style="color:black">|</i>
                    @Html.ActionLink("Về chúng tôi", "AboutUS", "WatchStore")
                </li>
                
            </ul>
        </div>
    </div>

</div>
<!--//banner -->
<section class="banner-bottom-wthreelayouts py-lg-5 py-3">
    <div class="container-fluid">

        <div class="inner-sec-shop px-lg-4 px-3">
            <div class="about-content py-lg-5 py-3">
                <div class="row">

                    <div class="col-lg-4 p-0">
                       
                        <img src="~/Content/images/banner4.jpg" alt="" height="450" />
                    </div>
                    <div class="col-lg-8 about-info">
                        <h3 class="tittle-w3layouts text-left mb-lg-5 mb-3">Về chúng tôi</h3>
                        <p class="my-xl-4 my-lg-3 my-md-4 my-3">
                            Khởi đầu kinh doanh từ năm 2020, Công ty TNHH Desc  bắt đầu xây dựng chuỗi hệ thống cửa hàng trưng bày và giới thiệu các sản phẩm đồng hồ cao cấp chính hãng tại thị trường Việt Nam. Mục tiêu kinh doanh của chúng tôi là cung cấp tới Khách hàng các sản phẩm Đồng hồ tốt chính hãng. Với tiêu trí kinh doanh bền vững, xây dựng uy tín dài lâu. Chúng tôi cam kết, tất cả đồng hồ được bán trực tiếp tại hệ thống các cửa hàng của chúng tôi và bán Online đều là hàng chính hãng 100%, chất lượng mới 100% được nhập khẩu nguyên chiếc từ  hãng, có xuất xứ kèm theo, có đầy đủ phụ kiện, có Thẻ/Sổ bảo hành Quốc tế đảm bảo đầy đủ quyền lợi bảo hành được qui định bởi bản hãng.
                        </p>

                        <a href="@Url.Action("Shop", "WatchStore")" class="btn btn-sm animated-button gibson-three mt-4">Mua Ngay</a>

                    </div>
                </div>
            </div>
            
            
            
            
        </div>
    </div>
</section>
<hr>

WatchStore/Views/WatchStore/Chude.cshtml
@model IEnumerable<WatchStore.Models.CHUDE>
<WebApplication1.Models.>

    <div class="banner-top container-fluid">
        <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light top-header mb-3">
                <button class="navbar-toggler mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav nav-mega mx-auto">
                        <li class="nav-item  nav-link">
                            @Html.ActionLink("Trang chủ", "Index", "WatchStore")
                        </li>
                        <li class="nav-item nav-link">
                            @Html.ActionLink("Chúng tôi", "AboutUS", "WatchStore")
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Loại
                            </a>
                            <ul class="dropdown-menu mega-menu ">
                                <li>
                                    <div class="row">
                                        @foreach (var item in Model)
                                        {
                                            <div class="col-md-4 media-list span4 text-left">
                                                <h5 class="tittle-w3layouts-sub">
                                                    <a href="@Url.Action("SPtheochude", "WatchStore", new { id = item.MaCD })" style="font-size:20pt; color:chartreuse">
                                                        @item.TenChuDe
                                                    </a>
                                                </h5>
                                            </div>
                                        }
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item nav-link">
                            @Html.ActionLink("Cửa hàng", "Shop", "WatchStore")
                        </li>
                        <li class="nav-item  nav-link">
                            @Html.ActionLink("Liên hệ", "Lienhe", "FeedBack")
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
    </div>

WatchStore/Views/WatchStore/Details.cshtml
@{
    ViewBag.Title = @Model.TenDH;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<hr>
<div class="banner_inner">
    <div class="services-breadcrumb">
        <div class="inner_breadcrumb">

            <ul class="short">
                <li>
                    @Html.ActionLink("Trang Chủ", "Index", "WatchStore")
                    <i style="color:black">|</i>
                    @Html.ActionLink("Sản Phẩm", "Details", "WatchStore")
                </li>
                
                
            </ul>
        </div>
    </div>

</div>
<!--//banner -->
<hr>
<section class="banner-bottom-wthreelayouts py-lg-5 py-3">
    <div class="container">
        <div class="inner-sec-shop pt-lg-4 pt-3">
            <div class="row">

                <div class="col-lg-5 single-right-left ">
                    <img alt="@Model.Anhbia" src="~/Content/images/@Model.Anhbia" data-imagezoom="true" class="img-fluid">
                </div>

                <div class="col-lg-7 single-right-left simpleCart_shelfItem">
                    <h3 style=" font-size:40px">@Model.TenDH</h3>
                    <hr />
                    <p>
                        Giá bán :

                        <span> @String.Format("{0:0,0}", @Model.Giaban) VNĐ</span>
                    </p>
                    <hr />
                    <p>
                        Số lượng tồn:
                        <span>@Model.Soluongton</span>
                    </p>
                    <hr />
                    <p>
                        Chất liệu:
                        <span>@Model.Chatlieu</span>
                    </p>
                    <hr />
                    <p>
                        Xuất xứ:
                        <span>@Model.MaNCC</span>
                    </p>
                    <hr />

                    <div id="Datmua">
                        <a href="@Url.Action("ThemGioHang","GioHang", new{@iMaDH =  @Model.MaDH, @strURL = Request.Url.ToString() })" class="btn btn-lg btn-success">
                            Thêm vào giỏ hàng
                        </a>
                    </div>



                </div>
                <div class="clearfix"> </div>


            </div>
        </div>
    </div>
</section>
<hr>

WatchStore/Views/WatchStore/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<!-- banner -->
<div class="banner-top container-fluid ">
    <div class="banner">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="carousel-caption text-center">
                        <h3>
                            Giảm giá sập sàn
                            <span>Mùa hè sôi động giảm đến 50%</span>
                        </h3>
                        <a href="@Url.Action("Shop", "WatchStore")" class="btn btn-s animated-button gibson-three mt-4">Mua Ngay</a>
                    </div>
                </div>
                <div class="carousel-item item2">
                    <div class="carousel-caption text-center">
                        <h3>
                            Đồng hồ nam
                            <span>Hãy lựa chọn cho mình một sản phẩm phù hợp trước khi rời khỏi website nhé</span>
                        </h3>
                        <a href="@Url.Action("Shop", "WatchStore")" class="btn btn-sm animated-button gibson-three mt-4">Mua Ngay</a>
                    </div>
                </div>
                <div class="carousel-item item3">
                    <div class="carousel-caption text-center">
                        <h3>
                            Đồng hồ nữ
                            <span>Hãy lựa chọn cho mình một sản phẩm phù hợp trước khi rời khỏi website nhé</span>
                        </h3>
                        <a href="@Url.Action("Shop", "WatchStore")" class="btn btn-lg animated-button gibson-three mt-4">Mua Ngay</a>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Trở về</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Tiếp theo</span>
            </a>
        </div>
        <!--//banner -->
    </div>
</div>
<!--//banner-sec-->

<h3 class="tittle-w3layouts my-lg-4 my-4">Sản phẩm mới</h3>
<div class="row">
    @foreach (var dongho in Model)
    {

        <div class=" col-md-3 product-men women_two">
            <div class="product-googles-info googles">
                <div class="men-pro-item">
                    <div class="men-thumb-item">
                        <a href="@Url.Action("Details", "WatchStore", new { @id = dongho.MaDH })">
                            <img alt="@dongho.Anhbia" src="~/Content/images/@dongho.Anhbia" />
                        </a>
                        <div class="men-cart-pro">
                            <div class="inner-men-cart-pro">
                                <a href="@Url.Action("Details","WatchStore", new { @id= dongho.MaDH})" class="link-product-add-cart">Xem</a>
                            </div>
                        </div>
                        <span class="product-new-top">Mới</span>
                    </div>
                    <div class="item-info-product">
                        <div class="info-product-price">
                            <div class="grid_meta">
                                <div class="product_price">
                                    <h4>
                                        <a href="single.html">@dongho.TenDH</a>
                                    </h4>
                                    <div class="grid-price mt-2">
                                        <span class="money">@dongho.Giaban  </span>
                                    </div>
                                </div>
                                <ul class="stars">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="googles single-item hvr-outline-out">
                                <form action="#" method="post">
                                    <input type="hidden" name="cmd" value="_cart">
                                    <input type="hidden" name="add" value="1">
                                    <button type="submit" class="googles-cart pgoogles-cart">
                                        <i class="fas fa-cart-plus"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="testimonials py-lg-4 py-3 mt-4">
    <div class="testimonials-inner py-lg-4 py-3">
        <h3 class="tittle-w3layouts text-center my-lg-4 my-4">Tiêu chí chọn một chiếc đồng hồ tốt</h3>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="testimonials_grid text-center">
                        <h3>
                            Thương hiệu
                        </h3>
                        <p>
                            Ngoài ra bây giờ trên thị trường có rất nhiều thương hiệu nổi tiếng khác trẻ trung hơn nhưng chất lượng cũng rất tốt. Vì vậy có rất nhiều lựa chọn, nên chọn đồng hồ đang được nhiều người dùng và có những phản hồi tốt  vì dù sao đấy chính là kiểm nghiệm chính xác nhất.
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="testimonials_grid text-center">
                        <h3>
                            Máy đồng hồ
                        </h3>
                        <p>
                            Đồng hồ điện tử thường chạy chính xác hơn. Nhưng nếu sở hữu một chiếc đồng hồ cơ tự động thì sẽ có nhiều người nhìn bạn bằng ánh mắt ngưỡng mộ hơn, vì chi phí sản xuất cao hơn do phải làm nhiều chi tiết hơn. Đồng hồ cơ đòi hỏi kỹ thuật tỉ mỉ hơn nên cần đến kinh nghiệm và tay nghề của các thợ sản xuất đồng hồ; cả hai thứ này đều không rẻ. Nguyên liệu làm đồng hồ cơ (vàng, đá quý, các kim loại đặc biệt) đắt tiền hơn; chế độ bảo hành phức tạp do có nhiều chi tiết hơn; hệ thống phân phối với số lượng ít hơn thì chi phí sẽ cao hơn.
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="testimonials_grid text-center">
                        <h3>
                            Mặt đồng hồ nào là tốt nhất?
                        </h3>
                        <p>
                            Mặt làm bằng mica dễ bị đàn hồi và xước nhưng dễ đánh bóng, làm mới. Mặt thuỷ tinh khoáng không đàn hồi chống nước tốt, khó xước hơn và cũng có thể đánh bóng khi bị xước.Mặt bằng saphia chống xước tốt nhất, chỉ xước nếu bị cọ với kim cương.
                        </p>
                    </div>
                </div>
                <a class="carousel-control-prev test" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="fas fa-long-arrow-alt-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next test" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="fas fa-long-arrow-alt-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>

                </a>
            </div>
        </div>
    </div>
</div>
<div class="row galsses-grids pt-lg-5 pt-3">
    <div class="col-lg-6 galsses-grid-left">
        <figure class="effect-lexi">
            <img src="~/Content/images/banner4.jpg" alt="" class="img-fluid">
            <figcaption>
                <h3>
                    Nhà bán hàng số 1
                    <span>Việt Nam</span>
                </h3>
                <p>
                    <a href="@Url.Action("Shop", "WatchStore" )" style="color:#f1c40f">Mua Ngay</a>

                </p>

            </figcaption>
        </figure>
    </div>
    <div class="col-lg-6 galsses-grid-left">
        <figure class="effect-lexi">
            <img src="~/Content/images/banner2.jpg" alt="" class="img-fluid">
            <figcaption>
                <h3>
                    Nhà phân phối số
                    <span>Việt Nam</span>
                </h3>
                
                <p>
                    <a href="@Url.Action("Shop", "WatchStore")" style="color:#f1c40f">Mua Ngay</a>

                </p>
            </figcaption>
        </figure>
    </div>
</div>

WatchStore/Views/WatchStore/SPtheochude.cshtml
@using WatchStore.Models
@{
    ViewBag.Title = "Sản phẩm theo chủ đề ";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="banner_inner">
    <div class="services-breadcrumb">
        <div class="inner_breadcrumb">

            <ul class="short">
                <li>
                    @Html.ActionLink("Trang Chủ", "Index", "WatchStore")
                    <i style="color:black">|</i>
                    @Html.ActionLink("Sản phẩm theo chủ đề", "SPtheochude", "Nguoidung")



                </li>

            </ul>
        </div>
    </div>

</div>
<!--//banner -->
<div class="row">

    @foreach (var dongho in Model)
    {
        <div class="col-md-3 product-men women_two">
            <div class="product-googles-info googles">
                <div class="men-pro-item">
                    <div class="men-thumb-item">
                        <a href="@Url.Action("Details", "WatchStore", new { id = dongho.MaDH })">
                            <img alt="@dongho.Anhbia" src="~/Content/images/@dongho.Anhbia" />
                        </a>
                        <div class="men-cart-pro">
                            <div class="inner-men-cart-pro">
                                <a href="@Url.Action("Details","WatchStore", new { @id= dongho.MaDH})" class="link-product-add-cart">Xem</a>
                            </div>
                        </div>
                        <span class="product-new-top">Mới</span>
                    </div>
                    <div class="item-info-product">
                        <div class="info-product-price">
                            <div class="grid_meta">
                                <div class="product_price">
                                    <h4>
                                        <a href="single.html">@dongho.TenDH</a>
                                    </h4>
                                    <div class="grid-price mt-2">
                                        <span>@dongho.Giaban  </span>
                                    </div>
                                </div>
                                <ul class="stars">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>